language: php

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${ILLUMINATE_VERSION}"

script:
  - composer test

matrix:
  include:
    - php: 7.3
      env: ILLUMINATE_VERSION=^6.0
    - php: 7.3
      env: ILLUMINATE_VERSION=^7.0
    - php: 7.3
      env: ILLUMINATE_VERSION=^8.0
    - php: 7.4
      env: ILLUMINATE_VERSION=^8.0
    - php: 8.0
      env: ILLUMINATE_VERSION=^8.0
